// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/contact": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/about" | "/contact";
  };
  "routes/_index.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/about.jsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/contact.jsx": {
    id: "routes/contact";
    page: "/contact";
  };
};