// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/favorites": {
    params: {};
  };
  "/:category": {
    params: {
      "category": string;
    };
  };
  "/:category/:subcategory": {
    params: {
      "category": string;
      "subcategory": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/favorites" | "/:category" | "/:category/:subcategory";
  };
  "routes/_index.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/favorites.jsx": {
    id: "routes/favorites";
    page: "/favorites";
  };
  "routes/$category.jsx": {
    id: "routes/$category";
    page: "/:category";
  };
  "routes/$category.$subcategory.jsx": {
    id: "routes/$category.$subcategory";
    page: "/:category/:subcategory";
  };
};